logging:
  file:
    name: 'logs/authentication-local.log'
    max-size: 500MB
    max-history: 10
  level:
    root: info
    com.seonjuleee.authentication-server: debug  # logger? ?? Hibernate ?? SQL ???

spring:
  config:
    import:
      - classpath:/config/datasource-local.yml

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      default-zone: http://localhost:8761/eureka