logging:
  file:
    name: 'logs/item-local.log'
    max-size: 500MB
    max-history: 10
  level:
    root: info
    org.hibernate.SQL: debug  # logger? ?? Hibernate ?? SQL ???

spring:
  config:
    import:
      - classpath:/config/datasource-local.yml

springdoc:
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  swagger-ui:
    operations-sorter: alpha # 정렬 기준, alpha : 알파벳 기준 오름차순
    tags-sorter: alpha
    path: /swagger-ui.html
    disable-swagger-default-url: true # 불필요한 내용 비활성화
    display-query-params-without-oauth2: true # URL 쿼리 매개변수를 이용해 swagger-ui 처리 활성화

token:
  expiration_time: 86400000

eureka:
  instance:
    instance-id: ${spring.cloud.client.hostname}:${spring.application.instance_id:${random.value}} # 호스트명과 랜덤포트를 합쳐 id 값으로 지정
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      default-zone: http://localhost:8761/eureka