logging:
  file:
    name: 'logs/item-local.log'
    max-size: 500MB
    max-history: 10
  level:
    root: info
    org.hibernate.SQL: debug  # logger? ?? Hibernate ?? SQL ???

spring:
  jpa:
    hibernate:
      ddl-auto: create  # create: ?????? ?? ??? ??? drop ? ?? ??
    properties:
      hibernate:
        show_sql: true  # System.out? Hibernate ?? SQL ???
        format_sql: true
  datasource:
    driver-class-name: org.h2.Driver
    url:  jdbc:h2:tcp://localhost/~/msa-lecture
    username: sa
    password:

springdoc:
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  swagger-ui:
    operations-sorter: alpha # 정렬 기준, alpha : 알파벳 기준 오름차순
    tags-sorter: alpha
    path: /swagger-ui.html
    disable-swagger-default-url: true # 불필요한 내용 비활성화
    display-query-params-without-oauth2: true # URL 쿼리 매개변수를 이용해 swagger-ui 처리 활성화

