logging:
  file:
    name: 'logs/item.log'
    max-size: 500MB
    max-history: 10
  level:
    root: info
    org.hibernate.SQL: debug  # logger? ?? Hibernate ?? SQL ???

spring:
  jpa:
    hibernate:
      ddl-auto: create  # create: ?????? ?? ??? ??? drop ? ?? ??
    properties:
      hibernate:
        show_sql: true  # System.out? Hibernate ?? SQL ???
        format_sql: true
  datasource:
    driver-class-name: org.h2.Driver
    url:  jdbc:h2:tcp://localhost/~/msa-lecture
    username: sa
    password: